# Generated by Django 3.2.12 on 2024-03-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment_commentdislike_commentlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='content',
        ),
    ]
