# Generated by Django 3.2.12 on 2024-03-24 13:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_alter_comment_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dislike',
            new_name='PostDislike',
        ),
        migrations.RenameModel(
            old_name='Like',
            new_name='PostLike',
        ),
    ]
